services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    ports:
      - "11434:11434"
    volumes:
      - /usr/share/ollama/.ollama:/root/.ollama # Replace with your actual host path
    environment:
      - OLLAMA_HOST=0.0.0.0
      # - OLLAMA_DEBUG=1
      - http_proxy=http://${DOCKER_HOST_IP}:10808
      - https_proxy=http://${DOCKER_HOST_IP}:10808
      - no_proxy=localhost,127.0.0.0/8,::1,api.deepseek.com,host.docker.internal,open-webui,pipelines

  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    restart: always
    depends_on:
      - ollama
      - pipelines
    extra_hosts:
      - "host.docker.internal:${DOCKER_HOST_IP}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    ports:
      - "127.0.0.1:3000:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - CUSTOM_NAME=智慧问答助手
      - WEBUI_NAME=智慧问答助手
      - GLOBAL_LOG_LEVEL=DEBUG
      - OLLAMA_BASE_URL=http://ollama:11434
      - RAG_EMBEDDING_ENGINE=ollama
      - RAG_OLLAMA_BASE_URL=http://ollama:11434
      - ENABLE_RAG_WEB_LOADER=true # If you want WebUI to be able to load from web for RAG
      - WEBUI_URL=https://ai.mister-hope.com
      - http_proxy=http://${DOCKER_HOST_IP}:10808
      - https_proxy=http://${DOCKER_HOST_IP}:10808
      - no_proxy=localhost,127.0.0.0/8,::1,api.deepseek.com,host.docker.internal,ollama,pipelines

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    volumes:
      - pipelines:/app/pipelines
    ports:
      - "9099:9099"
    restart: always
    environment:
      - PIPELINES_API_KEY=shigongwei-pipelines
      - http_proxy=http://${DOCKER_HOST_IP}:10808
      - https_proxy=http://${DOCKER_HOST_IP}:10808
      - no_proxy=localhost,127.0.0.0/8,::1,api.deepseek.com,host.docker.internal,open-webui,pipelines,ollama

volumes:
  open-webui:
    name: open-webui
    external: true

  pipelines:
    name: pipelines
    external: true
