services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    restart: always
    depends_on:
      - pipelines
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    ports:
      - "127.0.0.1:3000:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - CUSTOM_NAME=智慧问答助手
      - WEBUI_NAME=智慧问答助手
      - GLOBAL_LOG_LEVEL=DEBUG
      - OLLAMA_BASE_URL=http://ollama:11434
      - RAG_EMBEDDING_ENGINE=ollama
      - RAG_OLLAMA_BASE_URL=http://ollama:11434
      - ENABLE_RAG_WEB_LOADER=true # If you want WebUI to be able to load from web for RAG
      - WEBUI_URL=https://ai.mister-hope.com
      - http_proxy=http://${DOCKER_HOST_IP}:10808
      - https_proxy=http://${DOCKER_HOST_IP}:10808
      - no_proxy=localhost,127.0.0.0/8,::1,192.168.31.0/24,api.deepseek.com,host.docker.internal,ollama,pipelines
    networks:
      - default
      - ollama

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: open-webui-pipelines
    volumes:
      - pipelines:/app/pipelines
    ports:
      - "9099:9099"
    restart: always
    environment:
      - PIPELINES_API_KEY=shigongwei-pipelines
      - http_proxy=http://${DOCKER_HOST_IP}:10808
      - https_proxy=http://${DOCKER_HOST_IP}:10808
      - no_proxy=localhost,127.0.0.0/8,::1,192.168.31.0/24
    networks:
      - default

volumes:
  open-webui:
    name: open-webui
    external: true

  pipelines:
    name: pipelines
    external: true

networks:
  default:
    driver: bridge
    internal: true

  ollama:
    name: ollama
    external: true
