services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    ports:
      - "11434:11434"
    volumes:
      - /usr/share/ollama/.ollama:/root/.ollama # Replace with your actual host path
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama

networks:
  ollama:
    name: ollama
    external: true
