version: "3.8"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      # - OLLAMA_NEW_ENGINE=true
      - OLLAMA_DEBUG=1
      - OLLAMA_KEEP_ALIVE=-1
      - OLLAMA_CONTEXT_LENGTH=8192

volumes:
  ollama:
